### ISSUE TITLE
[Feat]: ERD screen basic UI styling

### ISSUE THREAD

**Issue by dbtkdfhr** [KMU-FlowERD/front-end#18]
## Overview

- ERD 프로젝트 화면 기초적인 UI 제작

## Tasks

- [x] 사이드 테이블, 관계 컴포넌트 제작
- [x] 하단 도구 메뉴  컴포넌트 제작
- [x] 테이블 컴포넌트 제작
